### ISSUE TITLE
Improvements to asynchronous HTTP function pages

### ISSUE THREAD

**Issue by YYBartT** [YoYoGames/GameMaker-Manual#154]
The manual's [Asynchronous HTTP Functions page](manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asynchronous_Functions/HTTP/HTTP.htm) currently lists all functions without providing a basic explanation of HTTP requests. It also lacks an overview on which function to use when. `http_request()` is the most "generic" function that can be used and `http_get()`, `http_get_file()` and `http_post_string()` can be used in more specific cases.

To be changed: 
- Add a short introduction to the asynchronous HTTP functions page and point out which function to use where/when. Link this introduction to a basic explanation of HTTP GET and POST requests (i.e. HTTP requests have a header and a body, body is optional, etc.).
- Add a complete code example on how to handle an HTTP request (or, alternatively, only a basic GET), complete with code in the async HTTP event that handles the entire request from start to end (i.e. from `async_load[? "status"]` equal to 1 up to the last event where it equals 0). Also add some code to the example that shows the progress bar.
- Make a clear distinction between URL parameters and request body.
- Possibly a few other things.

Brought up while doing changes for: https://github.com/YoYoGames/GameMaker-Bugs/issues/5744

**Comment by Emc1923** [comment]
Verified changes in the monthly manual, closing.
