### ISSUE TITLE
Improve Setting Up For Ubuntu page

### ISSUE THREAD

**Issue by samuelmacari** [YoYoGames/GameMaker-Manual#161]
Hi, so it's been a while and I still not see it in the page, but for those having Ubuntu via WSL, the page doesn't state that you need to install unzip (I remember that I had to scroll through the whole log to find this error), so it should be added to the list of packages to install.

I also had trouble connecting to Ubuntu WSL, and it might be needed for others, but after having installed openssh-server, sometimes it didn't work, I had to do this:
mkdir ~/.ssh
sudo /etc/init.d/ssh restart

**Comment by stuckie** [comment]
We only officially support Ubuntu as a fully installed OS - be that on a physical device or VM.
WSL is more of a container-like system, and may do different things as well as change things underneath more often, making it a moving target to try and support.
This is an unsupported configuration.
