### ISSUE TITLE
Confusing text in manual

### ISSUE THREAD

**Issue by YYBartT** [YoYoGames/GameMaker-Manual#200]
> Original helpdesk ticket: #215147

Description: The first sentence in this manual page says:

You can use this function to update the size of the view camera within the room.

I think it should rather say:

You can use this function to update the size of the view FOR A SPECIFIC camera within the room.

========
Beyond that, have you considered providing a more complete code example for working with camera and viewports?
As an example, one pretty obvious topic which remains unexplained is:
How to resize the game to maximum available size? Most of us are developing on 1920x1080 or similar screens, but then someone who has a 2K display tries the game and it's either running at a quarter of the screen area, or it's weirdly stretched.

Link: https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Cameras_And_Display/Cameras_And_Viewports/camera_set_view_size.htm

**Comment by YYDan** [comment]
Removed the bit about a secondary request for a more-expansive sample, as that has not been done for this issue.
