### ISSUE TITLE
Live Wallpaper guide missing Early Bird requirement

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Manual#226]
The live wallpaper guide https://help.gamemaker.io/hc/en-us/articles/10070287968285-How-To-Make-Live-Wallpapers-With-GameMaker does not detail the (new) requirement to enable Early Bird in opera GX settings

Enabling Early Bird requires a restart and then you can search for the Live Wallpaper app.

**Comment by gurpreetsinghmatharoo** [comment]
Updated
